# Generated by Django 4.1.5 on 2023-01-21 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(
                help_text="Duración en minutos de la película", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.URLField(
                blank=True,
                help_text="URL de la portada de la película",
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateField(blank=True, help_text="Fecha de lanzamiento", null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(blank=True, help_text="Sinopsis", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="trailer",
            field=models.URLField(
                blank=True,
                help_text="URL del trailer de la película",
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
