# Generated by Django 4.1.5 on 2023-01-21 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "picture",
                    models.URLField(
                        help_text="URL de la foto del director",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("first_name", models.CharField(help_text="Nombre", max_length=255)),
                ("last_name", models.CharField(help_text="Apellidos", max_length=255)),
                ("birth_date", models.DateField(help_text="Fecha de nacimiento")),
                (
                    "birth_country",
                    models.DateField(help_text="Lugar de nacimiento", max_length=50),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        help_text="Sexo",
                        max_length=1,
                    ),
                ),
                (
                    "biography",
                    models.TextField(
                        help_text="Información sobre la carrera del director",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("movies", models.ManyToManyField(help_text="Películas", to="movie.movie")),
            ],
        ),
    ]
