# Generated by Django 4.1.5 on 2023-01-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("director", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="birth_country",
            field=models.CharField(help_text="Lugar de nacimiento", max_length=50),
        ),
    ]
