# Generated by Django 4.1.5 on 2023-01-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
        ("director", "0002_alter_director_birth_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="birth_country",
            field=models.CharField(help_text="Lugar de nacimiento", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="birth_date",
            field=models.DateField(help_text="Fecha de nacimiento", null=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="movies",
            field=models.ManyToManyField(help_text="Películas", null=True, to="movie.movie"),
        ),
    ]
