# Generated by Django 4.1.5 on 2023-01-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
        ("director", "0003_alter_director_birth_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="director",
            name="biography",
            field=models.TextField(
                blank=True,
                help_text="Información sobre la carrera del director",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="birth_country",
            field=models.CharField(
                blank=True, help_text="Lugar de nacimiento", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="director",
            name="birth_date",
            field=models.DateField(blank=True, help_text="Fecha de nacimiento", null=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="movies",
            field=models.ManyToManyField(
                blank=True, help_text="Películas", null=True, to="movie.movie"
            ),
        ),
    ]
